# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(default='Usuario', max_length=100)),
                ('tipo', models.IntegerField(choices=[(0, 'Local'), (1, 'Remoto')], default=0)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha inicio prestamo')),
                ('fecha_fin', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha fin prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Recurso', max_length=100)),
                ('dependencia', models.IntegerField(choices=[(0, 'Ingenieria'), (1, 'Laboratorios'), (2, 'Biblioteca')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('correo', models.CharField(default='', max_length=100, unique=True)),
                ('telefono', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Usuario', max_length=100)),
                ('codigo', models.CharField(default='20091020077', max_length=100)),
                ('telefono', models.CharField(default='123435', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.Recurso')),
                ('marca', models.IntegerField(choices=[(0, 'Daweo'), (1, 'LG'), (2, 'Sony')], default=0)),
            ],
            bases=('prestamos.recurso',),
        ),
        migrations.CreateModel(
            name='EquipoElectronico',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.Recurso')),
                ('referencia', models.CharField(default='Referencia', max_length=100)),
                ('marca', models.IntegerField(choices=[(0, 'Daweo'), (1, 'LG'), (2, 'Sony')], default=0)),
            ],
            bases=('prestamos.recurso',),
        ),
        migrations.CreateModel(
            name='EspacioFisico',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.Recurso')),
                ('localizacion', models.CharField(default='Loc', max_length=100)),
            ],
            bases=('prestamos.recurso',),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.Recurso')),
            ],
            bases=('prestamos.recurso',),
        ),
        migrations.AddField(
            model_name='recurso',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Responsable'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Recurso'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.Usuario'),
        ),
        migrations.CreateModel(
            name='Auditorio',
            fields=[
                ('espaciofisico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.EspacioFisico')),
                ('sillas', models.IntegerField(default=1)),
            ],
            bases=('prestamos.espaciofisico',),
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('espaciofisico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.EspacioFisico')),
                ('capacidad', models.IntegerField(default=1)),
            ],
            bases=('prestamos.espaciofisico',),
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.Componente')),
                ('tipo', models.IntegerField(choices=[(0, 'HDMI'), (1, 'VGA')], default=0)),
            ],
            bases=('prestamos.componente',),
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('equipoelectronico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.EquipoElectronico')),
                ('tipo', models.IntegerField(choices=[(0, 'Portatil'), (1, 'Escritorio')], default=0)),
            ],
            bases=('prestamos.equipoelectronico',),
        ),
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.Servicio')),
                ('velocidad', models.IntegerField(default=1)),
                ('subred', models.CharField(default='Referencia', max_length=100)),
            ],
            bases=('prestamos.servicio',),
        ),
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('espaciofisico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.EspacioFisico')),
                ('bahias', models.IntegerField(default=1)),
            ],
            bases=('prestamos.espaciofisico',),
        ),
        migrations.CreateModel(
            name='PlacaElectronica',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.Componente')),
                ('tipo', models.IntegerField(choices=[(0, 'A'), (1, 'B')], default=0)),
            ],
            bases=('prestamos.componente',),
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('espaciofisico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.EspacioFisico')),
                ('sillas', models.IntegerField(default=1)),
            ],
            bases=('prestamos.espaciofisico',),
        ),
        migrations.CreateModel(
            name='VideoBeam',
            fields=[
                ('equipoelectronico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.EquipoElectronico')),
            ],
            bases=('prestamos.equipoelectronico',),
        ),
        migrations.CreateModel(
            name='VideoStreaming',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestamos.Servicio')),
                ('tipo', models.IntegerField(choices=[(0, 'Youtube'), (1, 'Otro')], default=0)),
            ],
            bases=('prestamos.servicio',),
        ),
    ]
